name: counter
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  flutter_lints: ^2.0.0
  flutter_pytorch: ^1.0.1
  image_picker: ^0.8.6
  gif: ^2.3.0
  flutter_svg: ^2.0.10+1
  sqflite: ^2.0.0+4
  path: ^1.8.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/models/
    - assets/labels/
    - assets/images/homescreen.jpeg
    - assets/images/homescreen.jpeg
    - assets/images/clsu.png
    - assets/images/icon2.png
    - assets/images/logo.png